name: build-run

on:
  push:
    branches:
      - master
    paths:
      - '**/*.c'
      - '**/*.h'
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc make tree check

    - name: Test project
      run: |
        cd test
        make test
